#'''
#   Author: Lauren Mak
#   Last updated: 10/17/2021
#'''

__default__:
    nCPU: 1
    mem: 8000
    output: "logs/{rule}.{wildcards}.%j.out"
    error: "logs/{rule}.{wildcards}.%j.err"
    job-name: "{rule}.{wildcards}"
    time: "7-00:00:00"


sra_download:
    mem : 2000
    nCPU: 10


kneaddata_bowtie:
    nCPU: 4
    mem: 100000


bayeshammer:
    nCPU: 15
    mem: 100000


sort:
    mem : 6000
    nCPU : 20


zip_file:
    nCPU: 1
    mem: 5000


spades:
    nCPU: 30
    mem: 250000


spades_coas:
    nCPU: 30
    mem: 350000


metawrap_binning:
    mem : 30000
    nCPU: 10


concoct_binning:
    mem : 10000
    nCPU: 10


metawrap_binning_coas:
    mem : 60000
    nCPU: 10


concoct_binning_coas:
    mem : 15000
    nCPU: 10


bin_refinement:
    mem : 50000
    nCPU: 5


bin_refinement_coas:
    mem : 75000
    nCPU: 5


checkm:
    mem: 130000
    nCPU: 10


checkm_coas:
    mem : 130000
    nCPU: 30


mashdist:
    mem : 1000
    nCPU: 1


dnadiff:
    mem : 5000
    nCPU: 2


prokka:
    mem : 2000
    nCPU : 2


prokka_coas:
    mem : 100000
    nCPU : 2


cmseq:
    mem : 4000
    nCPU : 2


cmseq_coas:
    mem : 10000
    nCPU : 2


dRep_95:
    mem : 10000
    nCPU : 30


dRep_95_coas:
    mem : 10000
    nCPU : 30


GTDB_TK:
    mem : 500000
    nCPU: 2


mapreads_scaffold:
    nCPU: 10
    mem: 5000


cat_MAGs:
    mem : 6000
    nCPU : 10


cat_MAGs_coas:
    mem : 6000
    nCPU : 10


readmap:
    mem : 5000
    nCPU: 10


readmap_coassembly:
    mem : 5000
    nCPU: 10
